# Generated by Django 3.2.16 on 2022-10-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='bookID',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='custID',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='book',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='_id',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
